name: tag-release
on:
  push:
    branches:
      - master
jobs:
  tag-release:
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release